# Generated by Django 4.2.15 on 2024-08-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("days", models.JSONField(default=list)),
            ],
            options={
                "verbose_name_plural": "Working Days",
                "unique_together": {("month", "year")},
            },
        ),
    ]
