# Generated by Django 4.2.15 on 2024-08-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender_app", "0002_workingdays"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workingdays",
            name="month",
            field=models.IntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ]
            ),
        ),
    ]
