# Generated by Django 4.2.15 on 2024-08-24 17:29

from django.db import migrations
import sender_app.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sender_app", "0003_alter_workingdays_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=sender_app.fields.EncryptedEmailField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="employeeresponse", unique_together={("employee", "date")},
        ),
    ]
