# Generated by Django 4.2.15 on 2024-08-28 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sender_app", "0004_alter_employee_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-08-28 23:30:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employeeresponse",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-08-28 23:30:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeeresponse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="workingdays",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-08-28 23:30:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workingdays",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="EmployeeEventResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "response",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sender_app.employee",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sender_app.event",
                    ),
                ),
            ],
            options={"unique_together": {("employee", "date", "event")},},
        ),
    ]
